# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-30 23:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='邮箱地址')),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('is_admin', models.BooleanField(default=False)),
                ('memo', models.TextField(blank=True, default=None, null=True, verbose_name='备注')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
