# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-31 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0005_auto_20170531_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='是否为管理员'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=32, verbose_name='用户名'),
        ),
    ]
